name: First Workflow (Lint, Test & Deploy on "Push")
on: [push]
jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Get code
        uses: actions/checkout@v3

      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Install dependencies
        run: npm cli
      
      - name: Run linter
        run: npm run lint

  test:
    needs: lint
    runs-on: ubuntu-22.04
    steps:
      - name: Get code
        uses: actions/checkout@v3

      - name: Install NodeJs
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Install dependencies
        run: npm cli

      - name: Run test
        run: npm run test

  deploy:
    needs: test
    runs-on: ubuntu-22.04
    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Install NodeJS
        uses: actions/setup-node@v3
        with: 
          node-version: "22"

      - name: Install dependencies
        run: npm ci

      - name: Build app
        run: npm run build

      - name: Show success message
        run: echo "App deployed successfully"